// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCWb2XxX8x8x8x8x8x8x8x8x8x8x8x8x8',
    appId: '1:569088266663:web:0000000000000000000000',
    messagingSenderId: '569088266663',
    projectId: 'listacomprasgetx',
    authDomain: 'listacomprasgetx.firebaseapp.com',
    storageBucket: 'listacomprasgetx.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCWb2XxX8x8x8x8x8x8x8x8x8x8x8x8x8',
    appId: '1:569088266663:android:0000000000000000000000',
    messagingSenderId: '569088266663',
    projectId: 'listacomprasgetx',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCWb2XxX8x8x8x8x8x8x8x8x8x8x8x8x8',
    appId: '1:569088266663:ios:0000000000000000000000',
    messagingSenderId: '569088266663',
    projectId: 'listacomprasgetx',
    iosBundleId: 'com.example.listaComprasGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCWb2XxX8x8x8x8x8x8x8x8x8x8x8x8x8',
    appId: '1:569088266663:ios:0000000000000000000000',
    messagingSenderId: '569088266663',
    projectId: 'listacomprasgetx',
    iosBundleId: 'com.example.listaComprasGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCWb2XxX8x8x8x8x8x8x8x8x8x8x8x8x8',
    appId: '1:569088266663:windows:0000000000000000000000',
    messagingSenderId: '569088266663',
    projectId: 'listacomprasgetx',
  );
}